import csv
import io
from datetime import UTC, date, datetime
from decimal import Decimal
from xml.sax.saxutils import escape
from zoneinfo import ZoneInfo

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.lead import Lead
from app.models.quotation import Quotation
from app.models.user import User

CSV_COLUMNS = (
    "Contact Name",
    "Company",
    "Email",
    "Phone",
    "Source",
    "Status",
    "Estimated Value",
    "Currency",
    "Notes",
    "Created At",
    "Updated At",
)

ENUM_LABELS = {
    "LINKEDIN": "LinkedIn",
    "UPWORK": "Upwork",
    "FIVERR": "Fiverr",
}


def _human_enum(value: object | None) -> str:
    if value is None:
        return ""
    raw = str(value)
    return ENUM_LABELS.get(raw, raw.replace("_", " ").title())


def _safe_csv_text(value: object | None) -> str:
    """Force formula-like user text to remain text when opened in a spreadsheet."""
    if value is None:
        return ""
    text = str(value)
    stripped = text.lstrip()
    if stripped.startswith(("=", "+", "-", "@")) or text.startswith(("\t", "\r")):
        return f"'{text}"
    return text


def _local_datetime(value: datetime, timezone_name: str) -> str:
    aware_value = value if value.tzinfo is not None else value.replace(tzinfo=UTC)
    return aware_value.astimezone(ZoneInfo(timezone_name)).strftime("%Y-%m-%d %H:%M:%S %Z")


def build_leads_csv(session: Session, user: User) -> bytes:
    leads = list(
        session.scalars(
            select(Lead)
            .where(Lead.owner_id == user.id, Lead.is_archived.is_(False))
            .order_by(Lead.created_at.desc(), Lead.id.desc())
        )
    )

    output = io.StringIO(newline="")
    writer = csv.writer(output, lineterminator="\r\n")
    writer.writerow(CSV_COLUMNS)
    for lead in leads:
        writer.writerow(
            (
                _safe_csv_text(lead.contact_name),
                _safe_csv_text(lead.company),
                _safe_csv_text(lead.email),
                _safe_csv_text(lead.phone),
                _human_enum(lead.source),
                _human_enum(lead.status),
                format(lead.estimated_value, ".2f"),
                user.currency_code,
                _safe_csv_text(lead.notes),
                _local_datetime(lead.created_at, user.timezone),
                _local_datetime(lead.updated_at, user.timezone),
            )
        )

    # A UTF-8 BOM makes Unicode reliable in Excel while remaining valid UTF-8 CSV.
    return ("\ufeff" + output.getvalue()).encode("utf-8")


def _pdf_text(value: object | None) -> str:
    if value is None:
        return ""
    return escape(str(value)).replace("\n", "<br/>")


def _pdf_line(value: object | None) -> str:
    """Keep single-line fields on one line so stray line breaks cannot create unsplittable rows."""
    if value is None:
        return ""
    return escape(" ".join(str(value).split()))


def _money(value: Decimal, currency_code: str) -> str:
    return f"{currency_code} {value:,.2f}"


def _draw_page_frame(canvas: object, document: SimpleDocTemplate) -> None:
    canvas.saveState()
    canvas.setStrokeColor(colors.HexColor("#E2E8F0"))
    canvas.line(document.leftMargin, 15 * mm, A4[0] - document.rightMargin, 15 * mm)
    canvas.setFillColor(colors.HexColor("#64748B"))
    canvas.setFont("Helvetica", 8)
    canvas.drawString(document.leftMargin, 10 * mm, "Generated by ClientFlow")
    canvas.drawRightString(
        A4[0] - document.rightMargin,
        10 * mm,
        f"Page {canvas.getPageNumber()}",
    )
    canvas.restoreState()


def build_quotation_pdf(quotation: Quotation, user: User) -> bytes:
    output = io.BytesIO()
    document = SimpleDocTemplate(
        output,
        pagesize=A4,
        rightMargin=16 * mm,
        leftMargin=16 * mm,
        topMargin=15 * mm,
        bottomMargin=21 * mm,
        title=f"Quotation {quotation.quote_number}",
        author=user.business_name,
        subject=f"Quotation for {quotation.lead.contact_name}",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "QuoteTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0F172A"),
        alignment=TA_RIGHT,
        spaceAfter=2 * mm,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#2563EB"),
        spaceAfter=2 * mm,
    )
    body_style = ParagraphStyle(
        "QuoteBody",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#334155"),
    )
    strong_style = ParagraphStyle(
        "QuoteStrong",
        parent=body_style,
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#0F172A"),
    )
    small_right = ParagraphStyle(
        "SmallRight",
        parent=body_style,
        fontSize=8,
        leading=12,
        alignment=TA_RIGHT,
    )

    business_lines = [
        Paragraph(_pdf_line(user.business_name), strong_style),
        Paragraph(_pdf_text(user.business_address), body_style),
        Paragraph(_pdf_line(user.business_phone), body_style),
        Paragraph(_pdf_line(user.email), body_style),
    ]
    quote_heading = [
        Paragraph("QUOTATION", title_style),
        Paragraph(_pdf_line(quotation.quote_number), small_right),
        Paragraph(f"Status: {_human_enum(quotation.status)}", small_right),
    ]
    header = Table([[business_lines, quote_heading]], colWidths=[110 * mm, 67 * mm])
    header.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    client_lines = [Paragraph(_pdf_line(quotation.lead.contact_name), strong_style)]
    for value in (quotation.lead.company, quotation.lead.email, quotation.lead.phone):
        if value:
            client_lines.append(Paragraph(_pdf_line(value), body_style))
    dates = [
        Paragraph(f"<b>Issue date</b><br/>{quotation.issue_date:%d %b %Y}", body_style),
        Paragraph(f"<b>Valid until</b><br/>{quotation.valid_until:%d %b %Y}", body_style),
    ]
    identity = Table(
        [
            [Paragraph("PREPARED FOR", heading_style), "", ""],
            [client_lines, dates[0], dates[1]],
        ],
        colWidths=[93 * mm, 42 * mm, 42 * mm],
    )
    identity.setStyle(
        TableStyle(
            [
                ("SPAN", (0, 0), (2, 0)),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
            ]
        )
    )

    item_rows: list[list[object]] = [
        [
            Paragraph("DESCRIPTION", heading_style),
            Paragraph("QTY", small_right),
            Paragraph("UNIT PRICE", small_right),
            Paragraph("AMOUNT", small_right),
        ]
    ]
    for item in quotation.items:
        item_rows.append(
            [
                Paragraph(_pdf_line(item.description), body_style),
                Paragraph(format(item.quantity, "f"), small_right),
                Paragraph(_money(item.unit_price, user.currency_code), small_right),
                Paragraph(_money(item.line_total, user.currency_code), small_right),
            ]
        )
    items_table = Table(
        item_rows,
        colWidths=[88 * mm, 20 * mm, 34 * mm, 35 * mm],
        repeatRows=1,
        splitByRow=True,
    )
    items_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EFF6FF")),
                ("LINEBELOW", (0, 0), (-1, 0), 0.8, colors.HexColor("#BFDBFE")),
                ("LINEBELOW", (0, 1), (-1, -1), 0.35, colors.HexColor("#E2E8F0")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 3 * mm),
                ("RIGHTPADDING", (0, 0), (-1, -1), 3 * mm),
                ("TOPPADDING", (0, 0), (-1, -1), 2.5 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5 * mm),
            ]
        )
    )

    total_rows = [
        ["Subtotal", _money(quotation.subtotal, user.currency_code)],
        [
            f"Discount ({quotation.discount_percent:.2f}%)",
            f"- {_money(quotation.discount_amount, user.currency_code)}",
        ],
        [f"Tax ({quotation.tax_percent:.2f}%)", _money(quotation.tax_amount, user.currency_code)],
        ["TOTAL", _money(quotation.total, user.currency_code)],
    ]
    totals = Table(total_rows, colWidths=[45 * mm, 45 * mm], hAlign="RIGHT")
    totals.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -2), "Helvetica"),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -2), 9),
                ("FONTSIZE", (0, -1), (-1, -1), 11),
                ("TEXTCOLOR", (0, 0), (-1, -2), colors.HexColor("#475569")),
                ("TEXTCOLOR", (0, -1), (-1, -1), colors.HexColor("#0F172A")),
                ("ALIGN", (1, 0), (1, -1), "RIGHT"),
                ("LINEABOVE", (0, -1), (-1, -1), 1, colors.HexColor("#94A3B8")),
                ("TOPPADDING", (0, 0), (-1, -1), 2 * mm),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 2 * mm),
            ]
        )
    )

    story: list[object] = [
        header,
        Spacer(1, 9 * mm),
        identity,
        Spacer(1, 7 * mm),
        items_table,
        Spacer(1, 5 * mm),
        totals,
    ]
    if quotation.notes:
        story.extend(
            [
                Spacer(1, 5 * mm),
                KeepTogether(
                    [
                        Paragraph("NOTES", heading_style),
                        Paragraph(_pdf_text(quotation.notes), body_style),
                    ]
                ),
            ]
        )

    document.build(story, onFirstPage=_draw_page_frame, onLaterPages=_draw_page_frame)
    return output.getvalue()


def leads_export_filename(today: date | None = None) -> str:
    return f"clientflow-leads-{today or date.today():%Y-%m-%d}.csv"
